-- custom types
create type public.app_permission as enum ('channels.delete', 'message.delete', 'record.delete')
create type public.app_role as enum ('admin', 'moderator')
create type public.user_status as enum ('ONLINE', "OFFLINE")

-- users
create table public.users (
  id          uuid not null primary key, -- uuid from user.auth
  username    text not null,
  email       text not null,
  status      user_status default 'OFFLINE'::public.user_status
);

-- channels
create table public.channels (
  id          bigint generated by default as identity primary key,
  created_by  uuid references public.users not null
);

-- user roles
create table public.user_roles (
  id          bigint generated by default as identity primary key,
  user_id     uuid references public.users on delete cascade not null,
  role        app_role not null,
  unique      (user_id, role)
);
comment on table public.user_roles is 'Application roles for each user.';

-- role premission
create table public.role_permission (
  id          bigint generated by default as identity primary key,
  role        app_role not null,
  premission  app_permission not null,
  unique      (role, premission)
);
comment on table public.role_permissions is 'Application permissions for each role.';